# Codacy configuration file
# This helps avoid false warnings and configures analysis behavior

engines:
  # Enable specific analysis engines for static website
  eslint:
    enabled: true
  csslint:
    enabled: true
  # Disable security scanners not applicable to static websites
  trivy:
    enabled: false
  semgrep:
    enabled: false
  bandit:
    enabled: false
  
exclude_patterns:
  # Exclude minified files and external libraries
  - 'assets/js/**/*.min.js'
  - 'assets/css/**/*.min.css'
  - 'assets/plugins/**'
  - 'assets/fonts/**'
  - 'node_modules/**'
  - '_site/**'
  - '.git/**'
  - '.github/**'
  # Exclude files that Trivy might try to scan inappropriately
  - '*.html'
  - '*.xml'
  - '*.json'
  - '*.md'
  - '*.txt'
  - '*.ico'
  - '*.png'
  - '*.jpg'
  - '*.jpeg'
  - '*.gif'
  - '*.svg'
  - '*.eot'
  - '*.woff'
  - '*.woff2'
  - '*.ttf'
  
# Ignore common false positives
duplication:
  config:
    languages:
      - javascript:
          mass_threshold: 100
      - css:
          mass_threshold: 50

# Tool-specific configurations
tools:
  eslint:
    exclude_patterns:
      - 'assets/js/bootstrap*.js'
      - 'assets/js/jquery*.js'