# Jekyll configuration for prajitdas.github.io
# Minimal public configuration

# Basic exclusions only
exclude:
  - .github/
  - "*.py"
  - "*.pyc"
  - "*.sh"
  - __pycache__/
  - .pytest_cache/
  - node_modules/

# Essential inclusions
include:
  - .well-known/
  - .well-known/keybase.txt

# Site settings (if needed)
plugins:
  - jekyll-sitemap

# Ensure .well-known files are processed correctly
keep_files:
  - .well-known

# Disable Jekyll processing for .well-known directory
defaults:
  - scope:
      path: ".well-known"
    values:
      sitemap: false