# Jekyll configuration for prajitdas.github.io
# Minimal public configuration

# Basic exclusions only
exclude:
  - .github/
  - "*.py"
  - "*.pyc"
  - "*.sh"
  - __pycache__/
  - .pytest_cache/
  - node_modules/

# Essential inclusions
include:
  - .well-known/

# Site settings (if needed)
plugins:
  - jekyll-sitemap